
[[constraint]]
  name = "github.com/caarlos0/spin"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "^1.19.1"
